repos:
  # isort
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort imports
        stages: [commit]
  # black
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        stages: [commit]
  # flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        stages: [commit]
  # pytest
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: venv/bin/pytest --picked -vvv --tb=long --failed-first -x
        always_run: true
        pass_filenames: false
        stages: [push]
  # requirements
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        language: system
        entry: bash -c 'venv/bin/pip freeze > requirements.txt; git add requirements.txt'
        pass_filenames: false
        stages: [commit]
